package com.its.springjwt.seleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import java.lang.Object;
//import org.openqa.selenium.support.ui.FluentWait<WebDriver>;
import org.junit.jupiter.api.Order;
import org.openqa.selenium.support.ui.WebDriverWait;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class T1_AdminLoginTest1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "E:\\Assignments\\S3 ITS Git Repository\\Backend\\springsecurityTest\\src\\main\\resources\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();

  }
  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  @Order(1)
  public void adminLoginTest1() {
    driver.get("http://localhost:8081/");
    driver.manage().window().setSize(new Dimension(1058, 628));
    driver.findElement(By.id("loginButtonNavbar")).click();
    driver.findElement(By.id("dropdown-form-email")).click();
    driver.findElement(By.id("dropdown-form-email")).sendKeys("Joro27");
    driver.findElement(By.id("__BVID__11__BV_label_")).click();
    driver.findElement(By.id("dropdown-form-password")).click();
    driver.findElement(By.id("dropdown-form-password")).sendKeys("12341234");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    ExplicitWait(driver, "Log Out");
    driver.findElement(By.cssSelector(".logoutbtn")).click();
    driver.findElement(By.cssSelector(".mt-3")).click();
  }

  public static void ExplicitWait(WebDriver driver, String text){
    (new WebDriverWait(driver, 3)).until(ExpectedConditions
            .elementToBeClickable(By.linkText(text)));
  }
}
