package com.its.springjwt.seleniumTests;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.junit.jupiter.api.Order;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class T3_EditUserTest1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "E:\\Assignments\\S3 ITS Git Repository\\Backend\\springsecurityTest\\src\\main\\resources\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Order(3)
  public void editUser() throws InterruptedException {
    driver.get("http://localhost:8081/");
    driver.manage().window().setSize(new Dimension(1062, 628));
    driver.findElement(By.id("loginButtonNavbar")).click();
    driver.findElement(By.id("dropdown-form-email")).click();
    driver.findElement(By.id("dropdown-form-email")).sendKeys("Joro27");
    driver.findElement(By.id("__BVID__11__BV_label_")).click();
    driver.findElement(By.id("dropdown-form-password")).click();
    driver.findElement(By.id("dropdown-form-password")).sendKeys("12341234");
    driver.findElement(By.cssSelector("#loginDropdownContent > form")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.cssSelector("h1:nth-child(3)")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".adminBtn")).click();
    driver.findElement(By.cssSelector("html")).click();
    driver.findElement(By.cssSelector("div:nth-child(16) .btn-warning")).click();
    driver.findElement(By.id("input-newUsername")).click();
    driver.findElement(By.id("input-newUsername")).sendKeys("Jaap2020");
    driver.findElement(By.id("bv-modal-edit___BV_modal_body_")).click();
    driver.findElement(By.id("bv-modal-edit___BV_modal_body_")).click();
    {
      WebElement element = driver.findElement(By.id("bv-modal-edit___BV_modal_body_"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id("input-newEmail")).click();
    driver.findElement(By.id("input-newEmail")).sendKeys("jaap12@gmail.com");
    driver.findElement(By.cssSelector(".mr-1")).click();
    driver.findElement(By.cssSelector("body > div:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".logoutbtn")).click();
    driver.findElement(By.id("__BVID__38___BV_modal_body_")).click();
    driver.findElement(By.cssSelector(".mt-3")).click();
  }
}
