package com.its.springjwt.seleniumTests;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.junit.jupiter.api.Order;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.HashMap;
import java.util.Map;

public class T4_Deleteusertest1 {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "E:\\Assignments\\S3 ITS Git Repository\\Backend\\springsecurityTest\\src\\main\\resources\\chromedriver.exe");
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  @Order(4)
  public void deleteUser() throws InterruptedException {
    driver.get("http://localhost:8081/");
    driver.manage().window().setSize(new Dimension(1062, 628));
    driver.findElement(By.id("loginButtonNavbar")).click();
    driver.findElement(By.id("dropdown-form-email")).click();
    driver.findElement(By.id("dropdown-form-email")).sendKeys("Joro27");
    driver.findElement(By.id("dropdown-form-password")).click();
    driver.findElement(By.id("dropdown-form-password")).sendKeys("12341234");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    Thread.sleep(1000);
    driver.findElement(By.cssSelector(".adminBtn")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".adminBtn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(16) .btn-danger")).click();
    driver.findElement(By.cssSelector(".mr-1")).click();
    driver.findElement(By.cssSelector(".logoutbtn")).click();
    driver.findElement(By.cssSelector(".mt-3")).click();
  }

  public static void ExplicitWait(WebDriver driver, String text){
    (new WebDriverWait(driver, 3)).until(ExpectedConditions
            .elementToBeClickable(By.className(text)));
  }
}
